# Setup
title:
  en: Joveler's Projects
  ko:  넓적부리의 프로젝트
tagline:
  en: <i class="fa fa-pie-chart"></i> Joveler
  ko: <i class="fa fa-pie-chart"></i> Joveler
index:
  en: index-en.html
  ko: index.html
baseurl:      ""
#paginate:     1

# About/contact
author:
  name:
    en: Joveler
    ko: Joveler
  url:        https://joveler.kr

# Gems
gems:
  - jekyll-paginate

# Collections
collections:
  - projects

#Others
markdown: kramdown
